version: '3.9'
services:
  redis:
   image: redis:7.0.0
   container_name: redis
   ports:
     - 6379:6379
   environment:
      - ALLOW_EMPTY_PASSWORD=yes
   volumes:
     - ./data/redis:/data
     - ./config/redis.conf:/path/to/redis.conf
   command: redis-server /path/to/redis.conf

  k6:
    image: loadimpact/k6
    container_name: k6
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/k6
    volumes:
      - ./scripts:/scripts
      
  influxdb:
    image: influxdb:1.8.10
    container_name: influxdb
    environment:
      - INFLUXDB_DB=k6
      - INFLUXDB_HTTP_MAX_BODY_SIZE=0
    ports: 
      - 8086:8086
    volumes: 
      - ./data/influxdb:/var/lib/influxdb

  grafana:
    image: grafana/grafana
    container_name: grafana
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    ports:
      - 3000:3000
    volumes:
      - ./data/grafana:/var/lib/grafana
  
  mariadb:
    image: mariadb
    container_name: mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=P@ssw0rd
      - MARIADB_DATABASE=goredismariadb
    ports:
      - 3306:3306
    volumes:
      - ./data/mariadb:/var/lib/mysql
    
   